# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "docker.io/fabergoncalves/pifanled:latest"
  amd64: "docker.io/fabergoncalves/pifanled:latest"
  armhf: "docker.io/fabergoncalves/pifanled:latest"
  armv7: "docker.io/fabergoncalves/pifanled:latest"
  i386: "docker.io/fabergoncalves/pifanled:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Pi Fan LED"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/fabergoncalves/pifanled-ha-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
