# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pi Fan LED
version: "1.2.0"
slug: example
description: Pi Fan LED
url: "https://github.com/fabergoncalves/pifanled-ha-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "docker.io/fabergoncalves/pifanled:latest"
