build_from:
  aarch64: docker.io/fabergoncalves/pifanled:latest
  amd64: docker.io/fabergoncalves/pifanled:latest
  armhf: docker.io/fabergoncalves/pifanled:latest
  armv7: docker.io/fabergoncalves/pifanled:latest
  i386: docker.io/fabergoncalves/pifanled:latest